version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./main.go
  - env:
      - CGO_ENABLED=0
    binary: rummage
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm
      - arm64
    flags:
      - -trimpath

checksum:
  name_template: "rummage_checksum.txt"
