name: Tests

on: [ push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        go: [stable]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Running tests
      run: go test -v ./...
